project:
  type: website
  output-dir: docs 

website:
  site-url: "https://lukaemon.github.io"
  description: "Lucas Shen blog"
  title: "Lucas Shen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukaemon
      - icon: twitter
        href: https://twitter.com/luka_emon
      - icon: rss
        href: index.xml
  twitter-card: true
  open-graph: true
  search:
    location: navbar
    type: textbox
  favicon: asset/logo.png
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true