project:
  type: website

website:
  title: "Lucas Shen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukaemon
      - icon: twitter
        href: https://twitter.com/luka_emon
  twitter-card: true
  open-graph: true
  search:
    location: navbar
    type: textbox
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true