project:
  type: website
  output-dir: docs

website:
  site-url: "https://lukaemon.github.io"
  description: "Lucas Shen blog"
  title: "Soliloquy"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukaemon
      - icon: twitter
        href: https://twitter.com/luka_emon
      - icon: rss
        href: index.xml
  twitter-card: true
  open-graph: true
  search:
    location: navbar
    type: textbox
  favicon: asset/logo.png

bibliography: asset/ref.bib

format:
  html:
    theme: spacelab
    toc: true